export type SystemdValueEnum = {
    directive: string;
    values: string[];
    section?: string;
    manPage?: string;
};
export const systemdValueEnum: ReadonlyArray<SystemdValueEnum> = [
    {
        directive: "BindIPv6Only",
        section: "Socket",
        manPage: "systemd.socket(5)",
        values: ["default", "both", "ipv6-only"],
    },
    {
        directive: "IPTOS",
        section: "Socket",
        manPage: "systemd.socket(5)",
        values: ["low-delay", "throughput", "reliability", "low-cost"],
    },
    {
        directive: "SocketProtocol",
        section: "Socket",
        manPage: "systemd.socket(5)",
        values: ["udplite", "sctp"],
    },
    {
        directive: "TCPCongestion",
        section: "Socket",
        manPage: "systemd.socket(5)",
        values: ["westwood", "veno", "cubic", "lp"],
    },
    {
        directive: "Timestamping",
        section: "Socket",
        manPage: "systemd.socket(5)",
        values: ["off", "us", "usec", "μs", "ns", "nsec"],
    },
    {
        directive: "CollectMode",
        section: "Unit",
        manPage: "systemd.unit(5)",
        values: ["inactive", "inactive-or-failed"],
    },
    {
        directive: "ConditionArchitecture",
        section: "Unit",
        manPage: "systemd.unit(5)",
        values: [
            "x86",
            "x86-64",
            "ppc",
            "ppc-le",
            "ppc64",
            "ppc64-le",
            "ia64",
            "parisc",
            "parisc64",
            "s390",
            "s390x",
            "sparc",
            "sparc64",
            "mips",
            "mips-le",
            "mips64",
            "mips64-le",
            "alpha",
            "arm",
            "arm-be",
            "arm64",
            "arm64-be",
            "sh",
            "sh64",
            "m68k",
            "tilegx",
            "cris",
            "arc",
            "arc-be",
            "native",
        ],
    },
    {
        directive: "ConditionVirtualization",
        section: "Unit",
        manPage: "systemd.unit(5)",
        values: ["vm", "container"],
    },
    {
        directive: "FailureAction",
        section: "Unit",
        manPage: "systemd.unit(5)",
        values: [
            "none",
            "reboot",
            "reboot-force",
            "reboot-immediate",
            "poweroff",
            "poweroff-force",
            "poweroff-immediate",
            "exit",
            "exit-force",
            "soft-reboot",
            "soft-reboot-force",
            "kexec",
            "kexec-force",
            "halt",
            "halt-force",
            "halt-immediate",
        ],
    },
    {
        directive: "BPFProgram",
        manPage: "systemd.resource-control(5)",
        values: [
            "egress",
            "ingress",
            "sock_create",
            "sock_ops",
            "device",
            "bind4",
            "bind6",
            "connect4",
            "connect6",
            "post_bind4",
            "post_bind6",
            "sendmsg4",
            "sendmsg6",
            "sysctl",
            "recvmsg4",
            "recvmsg6",
            "getsockopt",
            "setsockopt",
        ],
    },
    {
        directive: "MemoryPressureWatch",
        manPage: "systemd.resource-control(5)",
        values: ["off", "on", "auto", "skip"],
    },
    {
        directive: "CPUSchedulingPolicy",
        manPage: "systemd.exec(5)",
        values: ["other", "batch", "idle", "fifo", "rr"],
    },
    {
        directive: "IOSchedulingClass",
        manPage: "systemd.exec(5)",
        values: ["realtime", "best-effort", "idle"],
    },
    {
        directive: "KeyringMode",
        manPage: "systemd.exec(5)",
        values: ["inherit", "private", "shared"],
    },
    {
        directive: "Personality",
        manPage: "systemd.exec(5)",
        values: [
            "arm64",
            "arm64-be",
            "arm",
            "arm-be",
            "x86",
            "x86-64",
            "ppc",
            "ppc-le",
            "ppc64",
            "ppc64-le",
            "s390",
            "s390x",
        ],
    },
    {
        directive: "ProcSubset",
        manPage: "systemd.exec(5)",
        values: ["all", "pid"],
    },
    {
        directive: "ProtectProc",
        manPage: "systemd.exec(5)",
        values: ["noaccess", "invisible", "ptraceable", "default"],
    },
    {
        directive: "StandardInput",
        manPage: "systemd.exec(5)",
        values: ["null", "tty", "tty-force", "tty-fail", "data", "file:${path}", "socket", "fd:${name}"],
    },
    {
        directive: "StandardOutput",
        manPage: "systemd.exec(5)",
        values: [
            "inherit",
            "null",
            "tty",
            "journal",
            "kmsg",
            "journal+console",
            "kmsg+console",
            "file:${path}",
            "append:${path}",
            "truncate:${path}",
            "socket",
            "fd:${name}",
        ],
    },
    {
        directive: "SyslogFacility",
        manPage: "systemd.exec(5)",
        values: [
            "kern",
            "user",
            "mail",
            "daemon",
            "auth",
            "syslog",
            "lpr",
            "news",
            "uucp",
            "cron",
            "authpriv",
            "ftp",
            "local0",
            "local1",
            "local2",
            "local3",
            "local4",
            "local5",
            "local6",
            "local7",
        ],
    },
    {
        directive: "SyslogLevel",
        manPage: "systemd.exec(5)",
        values: ["emerg", "alert", "crit", "err", "warning", "notice", "info", "debug"],
    },
    {
        directive: "UtmpMode",
        manPage: "systemd.exec(5)",
        values: ["init", "login", "user"],
    },
    {
        directive: "ExitType",
        section: "Service",
        manPage: "systemd.service(5)",
        values: ["main", "cgroup"],
    },
    {
        directive: "FileDescriptorStorePreserve",
        section: "Service",
        manPage: "systemd.service(5)",
        values: ["no", "yes", "restart"],
    },
    {
        directive: "NotifyAccess",
        section: "Service",
        manPage: "systemd.service(5)",
        values: ["none", "main", "exec", "all"],
    },
    {
        directive: "OOMPolicy",
        section: "Service",
        manPage: "systemd.service(5)",
        values: ["continue", "stop", "kill"],
    },
    {
        directive: "Restart",
        section: "Service",
        manPage: "systemd.service(5)",
        values: ["no", "on-success", "on-failure", "on-abnormal", "on-watchdog", "on-abort", "always"],
    },
    {
        directive: "TimeoutStartFailureMode",
        section: "Service",
        manPage: "systemd.service(5)",
        values: ["terminate", "abort", "kill"],
    },
    {
        directive: "Type",
        section: "Service",
        manPage: "systemd.service(5)",
        values: ["simple", "exec", "forking", "oneshot", "dbus", "notify", "notify-reload", "idle"],
    },
    {
        directive: "OOMPolicy",
        manPage: "systemd.scope(5)",
        values: ["continue", "stop", "kill"],
    },
    {
        directive: "systemd.default_standard_error",
        manPage: "systemd(1)",
        values: [
            "inherit",
            "null",
            "tty",
            "journal",
            "journal+console",
            "kmsg",
            "kmsg+console",
        ],
    },
    {
        directive: "DefaultFileSystemType",
        section: "Home",
        manPage: "homed.conf(5)",
        values: ["btrfs", "ext4", "xfs"],
    },
    {
        directive: "DefaultStorage",
        section: "Home",
        manPage: "homed.conf(5)",
        values: ["luks", "fscrypt", "directory", "subvolume", "cifs"],
    },
    {
        directive: "ActivationPolicy",
        section: "Link",
        manPage: "systemd.network(5)",
        values: ["up", "always-up", "manual", "always-down", "down", "bound"],
    },
    {
        directive: "AssociatedWith",
        section: "BridgeFDB",
        manPage: "systemd.network(5)",
        values: ["use", "self", "master", "router"],
    },
    {
        directive: "ClientIdentifier",
        section: "DHCPv4",
        manPage: "systemd.network(5)",
        values: ["mac", "duid"],
    },
    {
        directive: "CompensationMode",
        section: "CAKE",
        manPage: "systemd.network(5)",
        values: ["none", "atm", "ptm"],
    },
    {
        directive: "DuplicateAddressDetection",
        section: "Address",
        manPage: "systemd.network(5)",
        values: ["ipv4", "ipv6", "both", "none"],
    },
    {
        directive: "FallbackLeaseLifetimeSec",
        section: "DHCPv4",
        manPage: "systemd.network(5)",
        values: ["forever", "infinity"],
    },
    {
        directive: "Family",
        section: "NextHop",
        manPage: "systemd.network(5)",
        values: ["ipv4", "ipv6"],
    },
    {
        directive: "IPMasquerade",
        section: "Network",
        manPage: "systemd.network(5)",
        values: ["ipv4", "ipv6", "both", "no"],
    },
    {
        directive: "IPServiceType",
        section: "DHCPv4",
        manPage: "systemd.network(5)",
        values: ["none", "CS6", "CS4"],
    },
    {
        directive: "IPv4ReversePathFilter",
        section: "Network",
        manPage: "systemd.network(5)",
        values: ["no", "strict", "loose"],
    },
    {
        directive: "IPv6LinkLocalAddressGenerationMode",
        section: "Network",
        manPage: "systemd.network(5)",
        values: ["eui64", "none", "stable-privacy", "random"],
    },
    {
        directive: "IPv6Preference",
        section: "Route",
        manPage: "systemd.network(5)",
        values: ["low", "medium", "high"],
    },
    {
        directive: "KeepConfiguration",
        section: "Network",
        manPage: "systemd.network(5)",
        values: ["static", "dhcp-on-stop", "dhcp"],
    },
    {
        directive: "MulticastRouter",
        section: "Bridge",
        manPage: "systemd.network(5)",
        values: ["no", "query", "permanent", "temporary"],
    },
    {
        directive: "Parent",
        section: "QuickFairQueueingClass",
        manPage: "systemd.network(5)",
        values: ["root"],
    },
    {
        directive: "Parent",
        section: "QuickFairQueueing",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "HeavyHitterFilter",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "HierarchyTokenBucketClass",
        manPage: "systemd.network(5)",
        values: ["root"],
    },
    {
        directive: "Parent",
        section: "HierarchyTokenBucket",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "TrivialLinkEqualizer",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "FairQueueing",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "FairQueueingControlledDelay",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "GenericRandomEarlyDetection",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "EnhancedTransmissionSelection",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "DeficitRoundRobinSchedulerClass",
        manPage: "systemd.network(5)",
        values: ["root"],
    },
    {
        directive: "Parent",
        section: "DeficitRoundRobinScheduler",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "ControlledDelay",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "CAKE",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "PFIFOFast",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "PFIFOHeadDrop",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "PFIFO",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "BFIFO",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "StochasticFairnessQueueing",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "StochasticFairBlue",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "FlowQueuePIE",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "PIE",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "TokenBucketFilter",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "NetworkEmulator",
        manPage: "systemd.network(5)",
        values: ["root", "clsact", "ingress"],
    },
    {
        directive: "Parent",
        section: "QDisc",
        manPage: "systemd.network(5)",
        values: ["clsact", "ingress"],
    },
    {
        directive: "RequiredFamilyForOnline",
        section: "Link",
        manPage: "systemd.network(5)",
        values: ["ipv4", "ipv6", "both", "any"],
    },
    {
        directive: "RouteTable",
        section: "IPv6AcceptRA",
        manPage: "systemd.network(5)",
        values: ["default", "main", "local"],
    },
    {
        directive: "RouteTable",
        section: "DHCPv4",
        manPage: "systemd.network(5)",
        values: ["default", "main", "local"],
    },
    {
        directive: "SendOption",
        section: "DHCPServer",
        manPage: "systemd.network(5)",
        values: ["uint8", "uint16", "uint32", "ipv4address", "ipv6address", "string"],
    },
    {
        directive: "SendOption",
        section: "DHCPv4",
        manPage: "systemd.network(5)",
        values: ["uint8", "uint16", "uint32", "ipv4address", "string"],
    },
    {
        directive: "SendVendorOption",
        section: "DHCPServer",
        manPage: "systemd.network(5)",
        values: ["uint8", "uint16", "uint32", "ipv4address", "string"],
    },
    {
        directive: "SendVendorOption",
        section: "DHCPv6",
        manPage: "systemd.network(5)",
        values: ["uint8", "uint16", "uint32", "ipv4address", "ipv6address", "string"],
    },
    {
        directive: "SendVendorOption",
        section: "DHCPv4",
        manPage: "systemd.network(5)",
        values: ["uint8", "uint16", "uint32", "ipv4address", "string"],
    },
    {
        directive: "Table",
        section: "Route",
        manPage: "systemd.network(5)",
        values: ["default", "main", "local"],
    },
    {
        directive: "Table",
        section: "RoutingPolicyRule",
        manPage: "systemd.network(5)",
        values: ["default", "main", "local"],
    },
    {
        directive: "Type",
        section: "Route",
        manPage: "systemd.network(5)",
        values: [
            "unicast",
            "local",
            "broadcast",
            "anycast",
            "multicast",
            "blackhole",
            "unreachable",
            "prohibit",
            "throw",
            "nat",
            "xresolve",
        ],
    },
    {
        directive: "Type",
        section: "RoutingPolicyRule",
        manPage: "systemd.network(5)",
        values: ["blackhole", "unreachable", "prohibit"],
    },
    {
        directive: "WithoutRA",
        section: "DHCPv6",
        manPage: "systemd.network(5)",
        values: ["no", "solicit", "information-request"],
    },
    {
        directive: "EncapsulationType",
        section: "L2TP",
        manPage: "systemd.netdev(5)",
        values: ["udp", "ip"],
    },
    {
        directive: "EtherType",
        section: "BareUDP",
        manPage: "systemd.netdev(5)",
        values: ["ipv4", "ipv6", "mpls-uc", "mpls-mc"],
    },
    {
        directive: "GatewayMode",
        section: "BatmanAdvanced",
        manPage: "systemd.netdev(5)",
        values: ["off", "server", "client"],
    },
    {
        directive: "Layer2SpecificHeader",
        section: "L2TPSession",
        manPage: "systemd.netdev(5)",
        values: ["none", "default"],
    },
    {
        directive: "Local",
        section: "Tunnel",
        manPage: "systemd.netdev(5)",
        values: ["any", "ipv4_link_local", "ipv6_link_local", "dhcp4", "dhcp6", "slaac"],
    },
    {
        directive: "Local",
        section: "VXLAN",
        manPage: "systemd.netdev(5)",
        values: ["ipv4_link_local", "ipv6_link_local", "dhcp4", "dhcp6", "slaac"],
    },
    {
        directive: "RouteTable",
        section: "WireGuardPeer",
        manPage: "systemd.netdev(5)",
        values: ["default", "main", "local"],
    },
    {
        directive: "RouteTable",
        section: "WireGuard",
        manPage: "systemd.netdev(5)",
        values: ["default", "main", "local"],
    },
    {
        directive: "Type",
        section: "WLAN",
        manPage: "systemd.netdev(5)",
        values: [
            "ad-hoc",
            "station",
            "ap",
            "ap-vlan",
            "wds",
            "monitor",
            "mesh-point",
            "p2p-client",
            "p2p-go",
            "p2p-device",
            "ocb",
            "nan",
        ],
    },
    {
        directive: "MDI",
        section: "Link",
        manPage: "systemd.link(5)",
        values: ["straight", "mdi", "crossover", "mdi-x", "mdix", "auto"],
    },
    {
        directive: "DNSStubListener",
        section: "Resolve",
        manPage: "resolved.conf(5)",
        values: ["udp", "tcp"],
    },
    {
        directive: "_LINE_BREAK",
        manPage: "systemd.journal-fields(7)",
        values: ["nul", "line-max", "eof", "pid-change"],
    },
    {
        directive: "class",
        manPage: "pam_systemd(8)",
        values: ["user", "greeter", "lock-screen", "background"],
    },
    {
        directive: "type",
        manPage: "pam_systemd(8)",
        values: ["unspecified", "tty", "x11", "wayland", "mir"],
    },
    {
        directive: "MaxLevelConsole",
        section: "Journal",
        manPage: "journald.conf(5)",
        values: ["emerg", "alert", "crit", "err", "warning", "notice", "info", "debug"],
    },
    {
        directive: "Storage",
        section: "Journal",
        manPage: "journald.conf(5)",
        values: ["volatile", "persistent", "auto", "none"],
    },
    {
        directive: "Storage",
        section: "Coredump",
        manPage: "coredump.conf(5)",
        values: ["none", "external", "journal"],
    },
    {
        directive: "HandleHibernateKey",
        section: "Login",
        manPage: "logind.conf(5)",
        values: [
            "ignore",
            "poweroff",
            "reboot",
            "halt",
            "kexec",
            "suspend",
            "hibernate",
            "hybrid-sleep",
            "suspend-then-hibernate",
            "lock",
            "factory-reset",
        ],
    },
    {
        directive: "IdleAction",
        section: "Login",
        manPage: "logind.conf(5)",
        values: [
            "ignore",
            "poweroff",
            "reboot",
            "halt",
            "kexec",
            "suspend",
            "hibernate",
            "hybrid-sleep",
            "suspend-then-hibernate",
            "lock",
        ],
    },
    {
        directive: "Storage",
        section: "PStore",
        manPage: "pstore.conf(5)",
        values: ["none", "external", "journal"],
    },
    {
        directive: "Encrypt",
        section: "Partition",
        manPage: "repart.d(5)",
        values: ["off", "key-file", "tpm2", "key-file+tpm2"],
    },
    {
        directive: "Minimize",
        section: "Partition",
        manPage: "repart.d(5)",
        values: ["off", "best", "guess"],
    },
    {
        directive: "Type",
        section: "Partition",
        manPage: "repart.d(5)",
        values: [
            "alpha",
            "arc",
            "arm",
            "arm64",
            "ia64",
            "loongarch64",
            "mips-le",
            "mips64-le",
            "parisc",
            "ppc",
            "ppc64",
            "ppc64-le",
            "riscv32",
            "riscv64",
            "s390",
            "s390x",
            "tilegx",
            "x86",
            "x86-64",
        ],
    },
    {
        directive: "Verity",
        section: "Partition",
        manPage: "repart.d(5)",
        values: ["off", "data", "hash", "signature"],
    },
    {
        directive: "PathRelativeTo",
        section: "Target",
        manPage: "sysupdate.d(5)",
        values: ["root", "esp", "xbootldr", "boot"],
    },
    {
        directive: "Type",
        section: "Target",
        manPage: "sysupdate.d(5)",
        values: ["partition", "regular-file", "directory", "subvolume"],
    },
    {
        directive: "Type",
        section: "Source",
        manPage: "sysupdate.d(5)",
        values: ["url-file", "url-tar", "tar", "regular-file", "directory", "subvolume"],
    },
];
