import { SystemdValueEnum } from "./types";

export const systemCallFilter: SystemdValueEnum = {
    manPage: "systemd.exec(5)",
    directive: "SystemCallFilter",
    prefixes: ["~"],
    sep: " ",
    docs: {
        _llseek: "reposition read/write file offset",
        _newselect: "synchronous I/O multiplexing",
        _sysctl: "Removed in 5.5   \nread/write system parameters",
        "@aio": "Asynchronous I/O ([io\\_setup(2)](https://man7.org/linux/man-pages/man2/io_setup.2.html), [io\\_submit(2)](https://man7.org/linux/man-pages/man2/io_submit.2.html), and related calls)",
        "@basic-io":
            "System calls for basic I/O: reading, writing, seeking, file descriptor duplication and closing ([read(2)](https://man7.org/linux/man-pages/man2/read.2.html), [write(2)](https://man7.org/linux/man-pages/man2/write.2.html), and related calls)",
        "@chown":
            "Changing file ownership ([chown(2)](https://man7.org/linux/man-pages/man2/chown.2.html), [fchownat(2)](https://man7.org/linux/man-pages/man2/fchownat.2.html), and related calls)",
        "@clock":
            "System calls for changing the system clock ([adjtimex(2)](https://man7.org/linux/man-pages/man2/adjtimex.2.html), [settimeofday(2)](https://man7.org/linux/man-pages/man2/settimeofday.2.html), and related calls)",
        "@cpu-emulation":
            "System calls for CPU emulation functionality ([vm86(2)](https://man7.org/linux/man-pages/man2/vm86.2.html) and related calls)",
        "@debug":
            "Debugging, performance monitoring and tracing functionality ([ptrace(2)](https://man7.org/linux/man-pages/man2/ptrace.2.html), [perf\\_event\\_open(2)](https://man7.org/linux/man-pages/man2/perf_event_open.2.html) and related calls)",
        "@file-system":
            "File system operations: opening, creating files and directories for read and write, renaming and removing them, reading file properties, or creating hard and symbolic links",
        "@io-event":
            "Event loop system calls ([poll(2)](https://man7.org/linux/man-pages/man2/poll.2.html), [select(2)](https://man7.org/linux/man-pages/man2/select.2.html), [epoll(7)](https://man7.org/linux/man-pages/man7/epoll.7.html), [eventfd(2)](https://man7.org/linux/man-pages/man2/eventfd.2.html) and related calls)",
        "@ipc": "Pipes, SysV IPC, POSIX Message Queues and other IPC ([mq\\_overview(7)](https://man7.org/linux/man-pages/man7/mq_overview.7.html), [svipc(7)](https://man7.org/linux/man-pages/man7/svipc.7.html))",
        "@keyring":
            "Kernel keyring access ([keyctl(2)](https://man7.org/linux/man-pages/man2/keyctl.2.html) and related calls)",
        "@known":
            "All system calls defined by the kernel. This list is defined statically in systemd based on a kernel version that was available when this systemd version was released. It will become progressively more out-of-date as the kernel is updated.",
        "@memlock":
            "Locking of memory in RAM ([mlock(2)](https://man7.org/linux/man-pages/man2/mlock.2.html), [mlockall(2)](https://man7.org/linux/man-pages/man2/mlockall.2.html) and related calls)",
        "@module":
            "Loading and unloading of kernel modules ([init\\_module(2)](https://man7.org/linux/man-pages/man2/init_module.2.html), [delete\\_module(2)](https://man7.org/linux/man-pages/man2/delete_module.2.html) and related calls)",
        "@mount":
            "Mounting and unmounting of file systems ([mount(2)](https://man7.org/linux/man-pages/man2/mount.2.html), [chroot(2)](https://man7.org/linux/man-pages/man2/chroot.2.html), and related calls)",
        "@network-io":
            "Socket I/O (including local AF\\_UNIX): [socket(7)](https://man7.org/linux/man-pages/man7/socket.7.html), [unix(7)](https://man7.org/linux/man-pages/man7/unix.7.html)",
        "@obsolete":
            "Unusual, obsolete or unimplemented ([create\\_module(2)](https://man7.org/linux/man-pages/man2/create_module.2.html), [gtty(2)](https://man7.org/linux/man-pages/man2/gtty.2.html), …)",
        "@pkey":
            "System calls that deal with memory protection keys ([pkeys(7)](https://man7.org/linux/man-pages/man7/pkeys.7.html))",
        "@privileged":
            "All system calls which need super-user capabilities ([capabilities(7)](https://man7.org/linux/man-pages/man7/capabilities.7.html))",
        "@process":
            "Process control, execution, namespacing operations ([clone(2)](https://man7.org/linux/man-pages/man2/clone.2.html), [kill(2)](https://man7.org/linux/man-pages/man2/kill.2.html), [namespaces(7)](https://man7.org/linux/man-pages/man7/namespaces.7.html), …)",
        "@raw-io":
            "Raw I/O port access ([ioperm(2)](https://man7.org/linux/man-pages/man2/ioperm.2.html), [iopl(2)](https://man7.org/linux/man-pages/man2/iopl.2.html), `pciconfig_read()`, …)",
        "@reboot":
            "System calls for rebooting and reboot preparation ([reboot(2)](https://man7.org/linux/man-pages/man2/reboot.2.html), `kexec()`, …)",
        "@resources":
            "System calls for changing resource limits, memory and scheduling parameters ([setrlimit(2)](https://man7.org/linux/man-pages/man2/setrlimit.2.html), [setpriority(2)](https://man7.org/linux/man-pages/man2/setpriority.2.html), …)",
        "@sandbox":
            "System calls for sandboxing programs ([seccomp(2)](https://man7.org/linux/man-pages/man2/seccomp.2.html), Landlock system calls, …)",
        "@setuid":
            "System calls for changing user ID and group ID credentials, ([setuid(2)](https://man7.org/linux/man-pages/man2/setuid.2.html), [setgid(2)](https://man7.org/linux/man-pages/man2/setgid.2.html), [setresuid(2)](https://man7.org/linux/man-pages/man2/setresuid.2.html), …)",
        "@signal":
            "System calls for manipulating and handling process signals ([signal(2)](https://man7.org/linux/man-pages/man2/signal.2.html), [sigprocmask(2)](https://man7.org/linux/man-pages/man2/sigprocmask.2.html), …)",
        "@swap":
            "System calls for enabling/disabling swap devices ([swapon(2)](https://man7.org/linux/man-pages/man2/swapon.2.html), [swapoff(2)](https://man7.org/linux/man-pages/man2/swapoff.2.html))",
        "@sync":
            "Synchronizing files and memory to disk ([fsync(2)](https://man7.org/linux/man-pages/man2/fsync.2.html), [msync(2)](https://man7.org/linux/man-pages/man2/msync.2.html), and related calls)",
        "@system-service":
            'A reasonable set of system calls used by common system services, excluding any special purpose calls. This is the recommended starting point for allow-listing system calls for system services, as it contains what is typically needed by system services, but excludes overly specific interfaces. For example, the following APIs are excluded: "`@clock`", "`@mount`", "`@swap`", "`@reboot`".',
        "@timer":
            "System calls for scheduling operations by time ([alarm(2)](https://man7.org/linux/man-pages/man2/alarm.2.html), [timer\\_create(2)](https://man7.org/linux/man-pages/man2/timer_create.2.html), …)",
        accept: "See notes on socketcall(2)   \naccept a connection on a socket",
        accept4: "accept a connection on a socket",
        access: "check user's permissions for a file",
        acct: "switch process accounting on or off",
        add_key: "add a key to the kernel's key management facility",
        adjtimex: "tune kernel clock",
        alarm: "set an alarm clock for delivery of a signal",
        alloc_hugepages: "Removed in 2.5.44   \nallocate or free huge pages",
        arc_gettls: "ARC only",
        arc_settls: "ARC only",
        arc_usr_cmpxchg: "ARC only",
        arch_prctl: "x86_64, x86 since 4.12   \nset architecture-specific thread state",
        atomic_barrier: "m68k only",
        atomic_cmpxchg_32: "m68k only",
        bdflush: "Deprecated (does nothing)since 2.6   \nstart, flush, or tune buffer-dirty-flush daemon",
        bind: "See notes on socketcall(2)   \nbind a name to a socket",
        bpf: "perform a command on an extended BPF map or program",
        breakpoint: "ARM OABI only, defined with<b>__ARM_NR </b>prefix",
        brk: "change data segment size",
        cacheflush: "Not on x86   \nflush contents of instruction and/or data cache",
        capget: "set/get capabilities of thread(s)",
        capset: "set/get capabilities of thread(s)",
        chdir: "change working directory",
        chmod: "change permissions of a file",
        chown: "See chown(2) for versiondetails   \nchange ownership of a file",
        chown32: "change ownership of a file",
        chroot: "change root directory",
        clock_adjtime: "tune kernel clock",
        clock_getres: "clock and time functions",
        clock_gettime: "clock and time functions",
        clock_nanosleep: "high-resolution sleep with specifiable clock",
        clock_settime: "clock and time functions",
        clone: "create a child process",
        clone2: "IA-64 only   \ncreate a child process",
        clone3: "create a child process",
        close: "close a file descriptor",
        close_range: "close all file descriptors in a given range",
        connect: "See notes on socketcall(2)   \ninitiate a connection on a socket",
        copy_file_range: "Copy a range of data from one file to another",
        creat: "open and possibly create a file",
        create_module: "Removed in 2.6   \ncreate a loadable module entry",
        delete_module: "unload a kernel module",
        dup: "duplicate a file descriptor",
        dup2: "duplicate a file descriptor",
        dup3: "duplicate a file descriptor",
        epoll_create: "open an epoll file descriptor",
        epoll_create1: "open an epoll file descriptor",
        epoll_ctl: "control interface for an epoll file descriptor",
        epoll_pwait: "wait for an I/O event on an epoll file descriptor",
        epoll_pwait2: "wait for an I/O event on an epoll file descriptor",
        epoll_wait: "wait for an I/O event on an epoll file descriptor",
        eventfd: "create a file descriptor for event notification",
        eventfd2: "create a file descriptor for event notification",
        execv: "SPARC/SPARC64 only, forcompatibility with SunOS",
        execve: "execute program",
        execveat: "execute program relative to a directory file descriptor",
        exit: "terminate the calling process",
        exit_group: "exit all threads in a process",
        faccessat: "check user's permissions for a file",
        faccessat2: "check user's permissions for a file",
        fadvise64: "predeclare an access pattern for file data",
        fadvise64_64: "predeclare an access pattern for file data",
        fallocate: "manipulate file space",
        fanotify_init: "create and initialize fanotify group",
        fanotify_mark: "add, remove, or modify an fanotify mark on a filesystem object",
        fchdir: "change working directory",
        fchmod: "change permissions of a file",
        fchmodat: "change permissions of a file",
        fchown: "change ownership of a file",
        fchown32: "change ownership of a file",
        fchownat: "change ownership of a file",
        fcntl: "manipulate file descriptor",
        fcntl64: "manipulate file descriptor",
        fdatasync: "synchronize a file's in-core state with storage device",
        fgetxattr: "retrieve an extended attribute value",
        finit_module: "load a kernel module",
        flistxattr: "list extended attribute names",
        flock: "apply or remove an advisory lock on an open file",
        fork: "create a child process",
        free_hugepages: "Removed in 2.5.44   \nallocate or free huge pages",
        fremovexattr: "remove an extended attribute",
        fsconfig: "",
        fsetxattr: "set an extended attribute value",
        fsmount: "",
        fsopen: "",
        fspick: "",
        fstat: "get file status",
        fstat64: "get file status",
        fstatat64: "get file status",
        fstatfs: "get filesystem statistics",
        fstatfs64: "get filesystem statistics",
        fsync: "synchronize a file's in-core state with storage device",
        ftruncate: "truncate a file to a specified length",
        ftruncate64: "truncate a file to a specified length",
        futex: "fast user-space locking",
        futimesat: "change timestamps of a file relative to a directory file descriptor",
        get_kernel_syms: "Removed in 2.6   \nretrieve exported kernel and module symbols",
        get_mempolicy: "retrieve NUMA memory policy for a thread",
        get_robust_list: "get/set list of robust futexes",
        get_thread_area: "manipulate thread-local storage information",
        get_tls: "ARM OABI only, has __ARM_NRprefix",
        getcpu: "determine CPU and NUMA node on which the calling thread is running",
        getcwd: "get current working directory",
        getdents: "get directory entries",
        getdents64: "get directory entries",
        getdomainname:
            "SPARC, SPARC64; availableas <b>osf_getdomainname</b>(2) onAlpha since Linux 2.0   \nget/set NIS domain name",
        getdtablesize: "SPARC (removed in 2.6.26),available on Alpha as<b>osf_getdtablesize</b>(2)",
        getegid: "get group identity",
        getegid32: "get group identity",
        geteuid: "get user identity",
        geteuid32: "get user identity",
        getgid: "get group identity",
        getgid32: "get group identity",
        getgroups: "get/set list of supplementary group IDs",
        getgroups32: "get/set list of supplementary group IDs",
        gethostname: "Alpha, was available onSPARC up to Linux 2.6.26   \nget/set hostname",
        getitimer: "get or set value of an interval timer",
        getpagesize: "Not on x86   \nget memory page size",
        getpeername: "See notes on socketcall(2)   \nget name of connected peer socket",
        getpgid: "set/get process group",
        getpgrp: "set/get process group",
        getpid: "get process identification",
        getppid: "get process identification",
        getpriority: "get/set program scheduling priority",
        getrandom: "obtain a series of random bytes",
        getresgid: "get real, effective and saved user/group IDs",
        getresgid32: "get real, effective, and saved user/group IDs",
        getresuid: "get real, effective and saved user/group IDs",
        getresuid32: "get real, effective, and saved user/group IDs",
        getrlimit: "get/set resource limits",
        getrusage: "get resource usage",
        getsid: "get session ID",
        getsockname: "See notes on socketcall(2)   \nget socket name",
        getsockopt: "See notes on socketcall(2)   \nget and set options on sockets",
        gettid: "get thread identification",
        gettimeofday: "get / set time",
        getuid: "get user identity",
        getuid32: "get user identity",
        getunwind: "IA-64 only; deprecated   \ncopy the unwind data to caller's buffer",
        getxattr: "retrieve an extended attribute value",
        getxgid: "Alpha only; see NOTES",
        getxpid: "Alpha only; see NOTES",
        getxuid: "Alpha only; see NOTES",
        init_module: "load a kernel module",
        inotify_add_watch: "add a watch to an initialized inotify instance",
        inotify_init: "initialize an inotify instance",
        inotify_init1: "initialize an inotify instance",
        inotify_rm_watch: "remove an existing watch from an inotify instance",
        io_cancel: "cancel an outstanding asynchronous I/O operation",
        io_destroy: "destroy an asynchronous I/O context",
        io_getevents: "read asynchronous I/O events from the completion queue",
        io_pgetevents: "",
        io_setup: "create an asynchronous I/O context",
        io_submit: "submit asynchronous I/O blocks for processing",
        io_uring_enter: "initiate and/or complete asynchronous I/O",
        io_uring_register: "register files or user buffers for asynchronous I/O",
        io_uring_setup: "setup a context for performing asynchronous I/O",
        ioctl: "control device",
        ioperm: "set port input/output permissions",
        iopl: "change I/O privilege level",
        ioprio_get: "get/set I/O scheduling class and priority",
        ioprio_set: "get/set I/O scheduling class and priority",
        ipc: "System V IPC system calls",
        kcmp: "compare two processes to determine if they share a kernel resource",
        kern_features: "SPARC64 only",
        kexec_file_load: "load a new kernel for later execution",
        kexec_load: "load a new kernel for later execution",
        keyctl: "manipulate the kernel's key management facility",
        kill: "send signal to a process",
        landlock_add_rule: "add a new Landlock rule to a ruleset",
        landlock_create_ruleset: "create a new Landlock ruleset",
        landlock_restrict_self: "enforce a Landlock ruleset",
        lchown: "See chown(2) for versiondetails   \nchange ownership of a file",
        lchown32: "change ownership of a file",
        lgetxattr: "retrieve an extended attribute value",
        link: "make a new name for a file",
        linkat: "make a new name for a file",
        listen: "See notes on socketcall(2)   \nlisten for connections on a socket",
        listxattr: "list extended attribute names",
        llistxattr: "list extended attribute names",
        lookup_dcookie: "return a directory entry's path",
        lremovexattr: "remove an extended attribute",
        lseek: "reposition read/write file offset",
        lsetxattr: "set an extended attribute value",
        lstat: "get file status",
        lstat64: "get file status",
        madvise: "give advice about use of memory",
        mbind: "set memory policy for a memory range",
        membarrier: "issue memory barriers on a set of threads",
        memfd_create: "create an anonymous file",
        memfd_secret: "create an anonymous RAM-based file to access secret memory regions",
        memory_ordering: "SPARC64 only",
        migrate_pages: "move all pages in a process to another set of nodes",
        mincore: "determine whether pages are resident in memory",
        mkdir: "create a directory",
        mkdirat: "create a directory",
        mknod: "create a special or ordinary file",
        mknodat: "create a special or ordinary file",
        mlock: "lock and unlock memory",
        mlock2: "lock and unlock memory",
        mlockall: "lock and unlock memory",
        mmap: "map or unmap files or devices into memory",
        mmap2: "map files or devices into memory",
        modify_ldt: "get or set a per-process LDT entry",
        mount: "mount filesystem",
        move_mount: "",
        move_pages: "move individual pages of a process to another node",
        mprotect: "set protection on a region of memory",
        mq_getsetattr: "get/set message queue attributes",
        mq_notify: "register for notification when a message is available",
        mq_open: "open a message queue",
        mq_timedreceive: "receive a message from a message queue",
        mq_timedsend: "send a message to a message queue",
        mq_unlink: "remove a message queue",
        mremap: "remap a virtual memory address",
        msgctl: "See notes on ipc(2)   \nSystem V message control operations",
        msgget: "See notes on ipc(2)   \nget a System V message queue identifier",
        msgrcv: "See notes on ipc(2)   \nSystem V message queue operations",
        msgsnd: "See notes on ipc(2)   \nSystem V message queue operations",
        msync: "synchronize a file with a memory map",
        munlock: "lock and unlock memory",
        munlockall: "lock and unlock memory",
        munmap: "map or unmap files or devices into memory",
        name_to_handle_at: "obtain handle for a pathname and open file via a",
        nanosleep: "high-resolution sleep",
        newfstatat: "See stat(2)   \nget file status",
        nfsservctl: "Removed in 3.1   \nsyscall interface to kernel nfs daemon",
        nice: "change process priority",
        old_adjtimex: "Alpha only; see NOTES",
        old_getrlimit: "Old variant of getrlimit(2)that used a different valuefor <b>RLIM_INFINITY</b>",
        oldfstat: "get file status",
        oldlstat: "get file status",
        oldolduname: "get name and information about current kernel",
        oldstat: "get file status",
        oldumount: "Name of the old umount(2)syscall on Alpha",
        olduname: "get name and information about current kernel",
        open: "open and possibly create a file",
        open_by_handle_at: "obtain handle for a pathname and open file via a",
        open_tree: "",
        openat: "open and possibly create a file",
        openat2: "open and possibly create a file (extended)",
        or1k_atomic: "OpenRISC 1000 only",
        pause: "wait for signal",
        pciconfig_iobase: "Not on x86   \npci device information handling",
        pciconfig_read: "Not on x86   \npci device information handling",
        pciconfig_write: "Not on x86   \npci device information handling",
        perf_event_open: "Was perf_counter_open() in2.6.31; renamed in 2.6.32   \nset up performance monitoring",
        perfctr: "SPARC only; removed in2.6.34",
        perfmonctl: "IA-64 only; removed in 5.10   \ninterface to IA-64 performance monitoring unit",
        personality: "set the process execution domain",
        pidfd_getfd: "obtain a duplicate of another process's file descriptor",
        pidfd_open: "obtain a file descriptor that refers to a process",
        pidfd_send_signal: "send a signal to a process specified by a file descriptor",
        pipe: "create pipe",
        pipe2: "create pipe",
        pivot_root: "change the root mount",
        pkey_alloc: "allocate or free a protection key",
        pkey_free: "allocate or free a protection key",
        pkey_mprotect: "set protection on a region of memory",
        poll: "wait for some event on a file descriptor",
        ppoll: "wait for some event on a file descriptor",
        prctl: "operations on a process or thread",
        pread64:
            'Added as "pread" in 2.2;renamed "pread64" in 2.6   \nread from or write to a file descriptor at a given offset',
        preadv: "read or write data into multiple",
        preadv2: "read or write data into multiple",
        prlimit64: "get/set resource limits",
        process_madvise: "give advice about use of memory to a process",
        process_vm_readv: "transfer data between process address spaces",
        process_vm_writev: "transfer data between process address spaces",
        pselect6: "synchronous I/O multiplexing",
        ptrace: "process trace",
        pwrite64:
            'Added as "pwrite" in 2.2;renamed "pwrite64" in 2.6   \nread from or write to a file descriptor at a given offset',
        pwritev: "read or write data into multiple",
        pwritev2: "read or write data into multiple",
        query_module: "Removed in 2.6   \nquery the kernel for various bits pertaining to modules",
        quotactl: "manipulate disk quotas",
        quotactl_fd: "",
        read: "read from a file descriptor",
        readahead: "initiate file readahead into page cache",
        readdir: "read directory entry",
        readlink: "read value of a symbolic link",
        readlinkat: "read value of a symbolic link",
        readv: "read or write data into multiple",
        reboot: "reboot or enable/disable Ctrl-Alt-Del",
        recv: "See notes on socketcall(2)   \nreceive a message from a socket",
        recvfrom: "See notes on socketcall(2)   \nreceive a message from a socket",
        recvmmsg: "receive multiple messages on a socket",
        recvmsg: "See notes on socketcall(2)   \nreceive a message from a socket",
        remap_file_pages: "Deprecated since 3.16   \ncreate a nonlinear file mapping",
        removexattr: "remove an extended attribute",
        rename: "change the name or location of a file",
        renameat: "change the name or location of a file",
        renameat2: "change the name or location of a file",
        request_key: "request a key from the kernel's key management facility",
        restart_syscall: "restart a system call after interruption by a stop signal",
        riscv_flush_icache: "RISC-V only",
        rmdir: "delete a directory",
        rseq: "",
        rt_sigaction: "examine and change a signal action",
        rt_sigpending: "examine pending signals",
        rt_sigprocmask: "examine and change blocked signals",
        rt_sigqueueinfo: "queue a signal and data",
        rt_sigreturn: "return from signal handler and cleanup stack frame",
        rt_sigsuspend: "wait for a signal",
        rt_sigtimedwait: "synchronously wait for queued signals",
        rt_tgsigqueueinfo: "queue a signal and data",
        rtas: "PowerPC/PowerPC64 only",
        s390_guarded_storage: "s390 only   \noperations with z/Architecture guarded storage facility",
        s390_pci_mmio_read: "s390 only   \ntransfer data to/from PCI MMIO memory page",
        s390_pci_mmio_write: "s390 only   \ntransfer data to/from PCI MMIO memory page",
        s390_runtime_instr: "s390 only   \nenable/disable s390 CPU run-time instrumentation",
        s390_sthyi: "s390 only   \nemulate STHYI instruction",
        sched_get_affinity:
            'Name of<a href="../man2/sched_getaffinity.2.html">sched_getaffinity(2)</a> onSPARC and SPARC64',
        sched_get_priority_max: "get static priority range",
        sched_get_priority_min: "get static priority range",
        sched_getaffinity: "set and get a thread's CPU affinity mask",
        sched_getattr: "set and get scheduling policy and attributes",
        sched_getparam: "set and get scheduling parameters",
        sched_getscheduler: "set and get scheduling policy/parameters",
        sched_rr_get_interval: "get the SCHED_RR interval for the named process",
        sched_set_affinity:
            'Name of<a href="../man2/sched_setaffinity.2.html">sched_setaffinity(2)</a> onSPARC and SPARC64',
        sched_setaffinity: "set and get a thread's CPU affinity mask",
        sched_setattr: "set and get scheduling policy and attributes",
        sched_setparam: "set and get scheduling parameters",
        sched_setscheduler: "set and get scheduling policy/parameters",
        sched_yield: "yield the processor",
        seccomp: "operate on Secure Computing state of the process",
        select: "synchronous I/O multiplexing",
        semctl: "See notes on ipc(2)   \nSystem V semaphore control operations",
        semget: "See notes on ipc(2)   \nget a System V semaphore set identifier",
        semop: "See notes on ipc(2)   \nSystem V semaphore operations",
        semtimedop: "System V semaphore operations",
        send: "See notes on socketcall(2)   \nsend a message on a socket",
        sendfile: "transfer data between file descriptors",
        sendfile64: "transfer data between file descriptors",
        sendmmsg: "send multiple messages on a socket",
        sendmsg: "See notes on socketcall(2)   \nsend a message on a socket",
        sendto: "See notes on socketcall(2)   \nsend a message on a socket",
        set_mempolicy: "set default NUMA memory policy for a thread and its children",
        set_robust_list: "get/set list of robust futexes",
        set_thread_area: "manipulate thread-local storage information",
        set_tid_address: "set pointer to thread ID",
        set_tls: "ARM OABI/EABI only(constant has <b>__ARM_NR</b>prefix)",
        setdomainname: "get/set NIS domain name",
        setfsgid: "set group identity used for filesystem checks",
        setfsgid32: "set group identity used for filesystem checks",
        setfsuid: "set user identity used for filesystem checks",
        setfsuid32: "set user identity used for filesystem checks",
        setgid: "set group identity",
        setgid32: "set group identity",
        setgroups: "get/set list of supplementary group IDs",
        setgroups32: "get/set list of supplementary group IDs",
        sethae: "Alpha only; see NOTES",
        sethostname: "get/set hostname",
        setitimer: "get or set value of an interval timer",
        setns: "reassociate thread with a namespace",
        setpgid: "set/get process group",
        setpgrp:
            'Alternative name for<a href="../man2/setpgid.2.html">setpgid(2)</a> on Alpha   \nset/get process group',
        setpriority: "get/set program scheduling priority",
        setregid: "set real and/or effective user or group ID",
        setregid32: "set real and/or effective user or group ID",
        setresgid: "set real, effective and saved user or group ID",
        setresgid32: "set real, effective, and saved user or group ID",
        setresuid: "set real, effective and saved user or group ID",
        setresuid32: "set real, effective, and saved user or group ID",
        setreuid: "set real and/or effective user or group ID",
        setreuid32: "set real and/or effective user or group ID",
        setrlimit: "get/set resource limits",
        setsid: "creates a session and sets the process group ID",
        setsockopt: "See notes on socketcall(2)   \nget and set options on sockets",
        settimeofday: "get / set time",
        setuid: "set user identity",
        setuid32: "set user identity",
        setup: "Removed in 2.2   \nsetup devices and filesystems, mount root filesystem",
        setxattr: "set an extended attribute value",
        sgetmask: "manipulation of signal mask (obsolete)",
        shmat: "See notes on ipc(2)   \nSystem V shared memory operations",
        shmctl: "See notes on ipc(2)   \nSystem V shared memory control",
        shmdt: "See notes on ipc(2)   \nSystem V shared memory operations",
        shmget: "See notes on ipc(2)   \nallocates a System V shared memory segment",
        shutdown: "See notes on socketcall(2)   \nshut down part of a full-duplex connection",
        sigaction: "examine and change a signal action",
        sigaltstack: "set and/or get signal stack context",
        signal: "ANSI C signal handling",
        signalfd: "create a file descriptor for accepting signals",
        signalfd4: "create a file descriptor for accepting signals",
        sigpending: "examine pending signals",
        sigprocmask: "examine and change blocked signals",
        sigreturn: "return from signal handler and cleanup stack frame",
        sigsuspend: "wait for a signal",
        socket: "See notes on socketcall(2)   \ncreate an endpoint for communication",
        socketcall: "socket system calls",
        socketpair: "See notes on socketcall(2)   \ncreate a pair of connected sockets",
        spill: "Xtensa only",
        splice: "splice data to/from a pipe",
        spu_create: "PowerPC/PowerPC64 only   \ncreate a new spu context",
        spu_run: "PowerPC/PowerPC64 only   \nexecute an SPU context",
        ssetmask: "manipulation of signal mask (obsolete)",
        stat: "get file status",
        stat64: "get file status",
        statfs: "get filesystem statistics",
        statfs64: "get filesystem statistics",
        statx: "get file status (extended)",
        stime: "set time",
        subpage_prot: "PowerPC/PowerPC64 only   \ndefine a subpage protection for an address range",
        swapcontext: "PowerPC/PowerPC64 only",
        swapoff: "start/stop swapping to file/device",
        swapon: "start/stop swapping to file/device",
        switch_endian: "PowerPC64 only",
        symlink: "make a new name for a file",
        symlinkat: "make a new name for a file",
        sync: "commit filesystem caches to disk",
        sync_file_range: "sync a file segment with disk",
        sync_file_range2: "sync a file segment with disk",
        syncfs: "commit filesystem caches to disk",
        sys_debug_setcontext: "PowerPC only",
        syscall: "Still available on ARM OABIand MIPS O32 ABI   \nindirect system call",
        sysfs: "get filesystem type information",
        sysinfo: "return system information",
        syslog: "read and/or clear kernel message ring buffer; set console_loglevel",
        sysmips: "MIPS only",
        tee: "duplicating pipe content",
        tgkill: "send a signal to a thread",
        time: "get time in seconds",
        timer_create: "create a POSIX per-process timer",
        timer_delete: "delete a POSIX per-process timer",
        timer_getoverrun: "get overrun count for a POSIX per-process timer",
        timer_gettime: "arm/disarm and fetch state of POSIX per-process timer",
        timer_settime: "arm/disarm and fetch state of POSIX per-process timer",
        timerfd_create: "timers that notify via file descrip‐",
        timerfd_gettime: "timers that notify via file descrip‐",
        timerfd_settime: "timers that notify via file descrip‐",
        times: "get process times",
        tkill: "send a signal to a thread",
        truncate: "truncate a file to a specified length",
        truncate64: "truncate a file to a specified length",
        ugetrlimit: "get/set resource limits",
        umask: "set file mode creation mask",
        umount: "unmount filesystem",
        umount2: "unmount filesystem",
        uname: "get name and information about current kernel",
        unlink: "delete a name and possibly the file it refers to",
        unlinkat: "delete a name and possibly the file it refers to",
        unshare: "disassociate parts of the process execution context",
        uselib: "load shared library",
        userfaultfd: "create a file descriptor for handling page faults in user space",
        usr26: "ARM OABI only",
        usr32: "ARM OABI only",
        ustat: "get filesystem statistics",
        utime: "change file last access and modification times",
        utimensat: "change file timestamps with nanosecond precision",
        utimes: "change file last access and modification times",
        utrap_install: "SPARC64 only",
        vfork: "create a child process and block parent",
        vhangup: "virtually hangup the current terminal",
        vm86: "enter virtual 8086 mode",
        vm86old: 'Was "vm86"; renamed in2.0.28/2.2   \nenter virtual 8086 mode',
        vmsplice: "splice user pages to/from a pipe",
        wait4: "wait for process to change state, BSD style",
        waitid: "wait for process to change state",
        waitpid: "wait for process to change state",
        write: "write to a file descriptor",
        writev: "read or write data into multiple",
        xtensa: "Xtensa only",
    },
    tips: {
        _llseek: "Kernal: 1.2",
        _newselect: "Kernal: 2.0",
        _sysctl: "Kernal: 2.0 ",
        "@aio": "Asynchronous I/O",
        "@basic-io": "System calls for basic I/O",
        "@chown": "Changing file ownership",
        "@clock": "System calls for changing the system clock",
        "@cpu-emulation": "System calls for CPU emulation functionality",
        "@debug": "Debugging, performance monitoring and tracing functionality",
        "@file-system": "File system operations",
        "@io-event": "Event loop system calls",
        "@ipc": "Pipes, SysV IPC, POSIX Message Queues and other IPC",
        "@keyring": "Kernel keyring access",
        "@known": "All system calls defined by the kernel",
        "@memlock": "Locking of memory in RAM",
        "@module": "Loading and unloading of kernel modules",
        "@mount": "Mounting and unmounting of file systems",
        "@network-io": "Socket I/O",
        "@obsolete": "Unusual, obsolete or unimplemented",
        "@pkey": "System calls that deal with memory protection keys",
        "@privileged": "All system calls which need super-user capabilities",
        "@process": "Process control, execution, namespacing operations",
        "@raw-io": "Raw I/O port access",
        "@reboot": "System calls for rebooting and reboot preparation",
        "@resources": "System calls for changing resource limits, memory and scheduling parameters",
        "@sandbox": "System calls for sandboxing programs",
        "@setuid": "System calls for changing user ID and group ID credentials,",
        "@signal": "System calls for manipulating and handling process signals",
        "@swap": "System calls for enabling/disabling swap devices",
        "@sync": "Synchronizing files and memory to disk",
        "@system-service":
            "A reasonable set of system calls used by common system services, excluding any special purpose calls",
        "@timer": "System calls for scheduling operations by time",
        accept: "Kernal: 2.0 ",
        accept4: "Kernal: 2.6.28",
        add_key: "Kernal: 2.6.10",
        alloc_hugepages: "Kernal: 2.5.36 ",
        arc_gettls: "Kernal: 3.9 ",
        arc_settls: "Kernal: 3.9 ",
        arc_usr_cmpxchg: "Kernal: 4.9 ",
        arch_prctl: "Kernal: 2.6 ",
        atomic_barrier: "Kernal: 2.6.34 ",
        atomic_cmpxchg_32: "Kernal: 2.6.34 ",
        bdflush: "Kernal: 1.2 ",
        bind: "Kernal: 2.0 ",
        bpf: "Kernal: 3.18",
        breakpoint: "Kernal: 2.2 ",
        cacheflush: "Kernal: 1.2 ",
        capget: "Kernal: 2.2",
        capset: "Kernal: 2.2",
        chown: "Kernal: 2.2 ",
        chown32: "Kernal: 2.4",
        clock_adjtime: "Kernal: 2.6.39",
        clock_getres: "Kernal: 2.6",
        clock_gettime: "Kernal: 2.6",
        clock_nanosleep: "Kernal: 2.6",
        clock_settime: "Kernal: 2.6",
        clone2: "Kernal: 2.4 ",
        clone3: "Kernal: 5.3",
        close_range: "Kernal: 5.9",
        connect: "Kernal: 2.0 ",
        copy_file_range: "Kernal: 4.5",
        create_module: "Kernal: 1.0 ",
        dup3: "Kernal: 2.6.27",
        epoll_create: "Kernal: 2.6",
        epoll_create1: "Kernal: 2.6.27",
        epoll_ctl: "Kernal: 2.6",
        epoll_pwait: "Kernal: 2.6.19",
        epoll_pwait2: "Kernal: 5.11",
        epoll_wait: "Kernal: 2.6",
        eventfd: "Kernal: 2.6.22",
        eventfd2: "Kernal: 2.6.27",
        execv: "Kernal: 2.0 ",
        execveat: "Kernal: 3.19",
        exit_group: "Kernal: 2.6",
        faccessat: "Kernal: 2.6.16",
        faccessat2: "Kernal: 5.8",
        fadvise64: "Kernal: 2.6",
        fadvise64_64: "Kernal: 2.6",
        fallocate: "Kernal: 2.6.23",
        fanotify_init: "Kernal: 2.6.37",
        fanotify_mark: "Kernal: 2.6.37",
        fchmodat: "Kernal: 2.6.16",
        fchown32: "Kernal: 2.4",
        fchownat: "Kernal: 2.6.16",
        fcntl64: "Kernal: 2.4",
        fdatasync: "Kernal: 2.0",
        fgetxattr: "Kernal: 2.6; 2.4.18",
        finit_module: "Kernal: 3.8",
        flistxattr: "Kernal: 2.6; 2.4.18",
        flock: "Kernal: 2.0",
        free_hugepages: "Kernal: 2.5.36 ",
        fremovexattr: "Kernal: 2.6; 2.4.18",
        fsconfig: "Kernal: 5.2",
        fsetxattr: "Kernal: 2.6; 2.4.18",
        fsmount: "Kernal: 5.2",
        fsopen: "Kernal: 5.2",
        fspick: "Kernal: 5.2",
        fstat64: "Kernal: 2.4",
        fstatat64: "Kernal: 2.6.16",
        fstatfs64: "Kernal: 2.6",
        ftruncate64: "Kernal: 2.4",
        futex: "Kernal: 2.6",
        futimesat: "Kernal: 2.6.16",
        get_kernel_syms: "Kernal: 1.0 ",
        get_mempolicy: "Kernal: 2.6.6",
        get_robust_list: "Kernal: 2.6.17",
        get_thread_area: "Kernal: 2.6",
        get_tls: "Kernal: 4.15 ",
        getcpu: "Kernal: 2.6.19",
        getcwd: "Kernal: 2.2",
        getdents: "Kernal: 2.0",
        getdents64: "Kernal: 2.4",
        getdomainname: "Kernal: 2.2 ",
        getdtablesize: "Kernal: 2.0 ",
        getegid32: "Kernal: 2.4",
        geteuid32: "Kernal: 2.4",
        getgid32: "Kernal: 2.4",
        getgroups32: "Kernal: 2.4",
        gethostname: "Kernal: 2.0 ",
        getpagesize: "Kernal: 2.0 ",
        getpeername: "Kernal: 2.0 ",
        getrandom: "Kernal: 3.17",
        getresgid: "Kernal: 2.2",
        getresgid32: "Kernal: 2.4",
        getresuid: "Kernal: 2.2",
        getresuid32: "Kernal: 2.4",
        getsid: "Kernal: 2.0",
        getsockname: "Kernal: 2.0 ",
        getsockopt: "Kernal: 2.0 ",
        gettid: "Kernal: 2.4.11",
        getuid32: "Kernal: 2.4",
        getunwind: "Kernal: 2.4.8 ",
        getxattr: "Kernal: 2.6; 2.4.18",
        getxgid: "Kernal: 2.0 ",
        getxpid: "Kernal: 2.0 ",
        getxuid: "Kernal: 2.0 ",
        inotify_add_watch: "Kernal: 2.6.13",
        inotify_init: "Kernal: 2.6.13",
        inotify_init1: "Kernal: 2.6.27",
        inotify_rm_watch: "Kernal: 2.6.13",
        io_cancel: "Kernal: 2.6",
        io_destroy: "Kernal: 2.6",
        io_getevents: "Kernal: 2.6",
        io_pgetevents: "Kernal: 4.18",
        io_setup: "Kernal: 2.6",
        io_submit: "Kernal: 2.6",
        io_uring_enter: "Kernal: 5.1",
        io_uring_register: "Kernal: 5.1",
        io_uring_setup: "Kernal: 5.1",
        ioprio_get: "Kernal: 2.6.13",
        ioprio_set: "Kernal: 2.6.13",
        kcmp: "Kernal: 3.5",
        kern_features: "Kernal: 3.7 ",
        kexec_file_load: "Kernal: 3.17",
        kexec_load: "Kernal: 2.6.13",
        keyctl: "Kernal: 2.6.10",
        landlock_add_rule: "Kernal: 5.13",
        landlock_create_ruleset: "Kernal: 5.13",
        landlock_restrict_self: "Kernal: 5.13",
        lchown: "Kernal: 1.0 ",
        lchown32: "Kernal: 2.4",
        lgetxattr: "Kernal: 2.6; 2.4.18",
        linkat: "Kernal: 2.6.16",
        listen: "Kernal: 2.0 ",
        listxattr: "Kernal: 2.6; 2.4.18",
        llistxattr: "Kernal: 2.6; 2.4.18",
        lookup_dcookie: "Kernal: 2.6",
        lremovexattr: "Kernal: 2.6; 2.4.18",
        lsetxattr: "Kernal: 2.6; 2.4.18",
        lstat64: "Kernal: 2.4",
        madvise: "Kernal: 2.4",
        mbind: "Kernal: 2.6.6",
        membarrier: "Kernal: 3.17",
        memfd_create: "Kernal: 3.17",
        memfd_secret: "Kernal: 5.14",
        memory_ordering: "Kernal: 2.2 ",
        migrate_pages: "Kernal: 2.6.16",
        mincore: "Kernal: 2.4",
        mkdirat: "Kernal: 2.6.16",
        mknodat: "Kernal: 2.6.16",
        mlock: "Kernal: 2.0",
        mlock2: "Kernal: 4.4",
        mlockall: "Kernal: 2.0",
        mmap2: "Kernal: 2.4",
        move_mount: "Kernal: 5.2",
        move_pages: "Kernal: 2.6.18",
        mq_getsetattr: "Kernal: 2.6.6",
        mq_notify: "Kernal: 2.6.6",
        mq_open: "Kernal: 2.6.6",
        mq_timedreceive: "Kernal: 2.6.6",
        mq_timedsend: "Kernal: 2.6.6",
        mq_unlink: "Kernal: 2.6.6",
        mremap: "Kernal: 2.0",
        msgctl: "Kernal: 2.0 ",
        msgget: "Kernal: 2.0 ",
        msgrcv: "Kernal: 2.0 ",
        msgsnd: "Kernal: 2.0 ",
        msync: "Kernal: 2.0",
        munlock: "Kernal: 2.0",
        munlockall: "Kernal: 2.0",
        name_to_handle_at: "Kernal: 2.6.39",
        nanosleep: "Kernal: 2.0",
        newfstatat: "Kernal: 2.6.16 ",
        nfsservctl: "Kernal: 2.2 ",
        old_adjtimex: "Kernal: 2.0 ",
        old_getrlimit: "Kernal: 2.4 ",
        oldumount: "Kernal: 2.4.116 ",
        open_by_handle_at: "Kernal: 2.6.39",
        open_tree: "Kernal: 5.2",
        openat: "Kernal: 2.6.16",
        openat2: "Kernal: 5.6",
        or1k_atomic: "Kernal: 3.1 ",
        pciconfig_iobase: "Kernal: 2.2.15; 2.4 ",
        pciconfig_read: "Kernal: 2.0.26; 2.2 ",
        pciconfig_write: "Kernal: 2.0.26; 2.2 ",
        perf_event_open: "Kernal: 2.6.31 ",
        perfctr: "Kernal: 2.2 ",
        perfmonctl: "Kernal: 2.4 ",
        personality: "Kernal: 1.2",
        pidfd_getfd: "Kernal: 5.6",
        pidfd_open: "Kernal: 5.3",
        pidfd_send_signal: "Kernal: 5.1",
        pipe2: "Kernal: 2.6.27",
        pivot_root: "Kernal: 2.4",
        pkey_alloc: "Kernal: 4.8",
        pkey_free: "Kernal: 4.8",
        pkey_mprotect: "Kernal: 4.8",
        poll: "Kernal: 2.0.36; 2.2",
        ppoll: "Kernal: 2.6.16",
        prctl: "Kernal: 2.2",
        preadv: "Kernal: 2.6.30",
        preadv2: "Kernal: 4.6",
        prlimit64: "Kernal: 2.6.36",
        process_madvise: "Kernal: 5.10",
        process_vm_readv: "Kernal: 3.2",
        process_vm_writev: "Kernal: 3.2",
        pselect6: "Kernal: 2.6.16",
        pwritev: "Kernal: 2.6.30",
        pwritev2: "Kernal: 4.6",
        query_module: "Kernal: 2.2 ",
        quotactl_fd: "Kernal: 5.14",
        readahead: "Kernal: 2.4.13",
        readlinkat: "Kernal: 2.6.16",
        readv: "Kernal: 2.0",
        recv: "Kernal: 2.0 ",
        recvfrom: "Kernal: 2.0 ",
        recvmmsg: "Kernal: 2.6.33",
        recvmsg: "Kernal: 2.0 ",
        remap_file_pages: "Kernal: 2.6 ",
        removexattr: "Kernal: 2.6; 2.4.18",
        renameat: "Kernal: 2.6.16",
        renameat2: "Kernal: 3.15",
        request_key: "Kernal: 2.6.10",
        restart_syscall: "Kernal: 2.6",
        riscv_flush_icache: "Kernal: 4.15 ",
        rseq: "Kernal: 4.18",
        rt_sigaction: "Kernal: 2.2",
        rt_sigpending: "Kernal: 2.2",
        rt_sigprocmask: "Kernal: 2.2",
        rt_sigqueueinfo: "Kernal: 2.2",
        rt_sigreturn: "Kernal: 2.2",
        rt_sigsuspend: "Kernal: 2.2",
        rt_sigtimedwait: "Kernal: 2.2",
        rt_tgsigqueueinfo: "Kernal: 2.6.31",
        rtas: "Kernal: 2.6.2 ",
        s390_guarded_storage: "Kernal: 4.12 ",
        s390_pci_mmio_read: "Kernal: 3.19 ",
        s390_pci_mmio_write: "Kernal: 3.19 ",
        s390_runtime_instr: "Kernal: 3.7 ",
        s390_sthyi: "Kernal: 4.15 ",
        sched_get_affinity: "Kernal: 2.6 ",
        sched_get_priority_max: "Kernal: 2.0",
        sched_get_priority_min: "Kernal: 2.0",
        sched_getaffinity: "Kernal: 2.6",
        sched_getattr: "Kernal: 3.14",
        sched_getparam: "Kernal: 2.0",
        sched_getscheduler: "Kernal: 2.0",
        sched_rr_get_interval: "Kernal: 2.0",
        sched_set_affinity: "Kernal: 2.6 ",
        sched_setaffinity: "Kernal: 2.6",
        sched_setattr: "Kernal: 3.14",
        sched_setparam: "Kernal: 2.0",
        sched_setscheduler: "Kernal: 2.0",
        sched_yield: "Kernal: 2.0",
        seccomp: "Kernal: 3.17",
        semctl: "Kernal: 2.0 ",
        semget: "Kernal: 2.0 ",
        semop: "Kernal: 2.0 ",
        semtimedop: "Kernal: 2.6; 2.4.22",
        send: "Kernal: 2.0 ",
        sendfile: "Kernal: 2.2",
        sendfile64: "Kernal: 2.6; 2.4.19",
        sendmmsg: "Kernal: 3.0",
        sendmsg: "Kernal: 2.0 ",
        sendto: "Kernal: 2.0 ",
        set_mempolicy: "Kernal: 2.6.6",
        set_robust_list: "Kernal: 2.6.17",
        set_thread_area: "Kernal: 2.6",
        set_tid_address: "Kernal: 2.6",
        set_tls: "Kernal: 2.6.11 ",
        setfsgid: "Kernal: 1.2",
        setfsgid32: "Kernal: 2.4",
        setfsuid: "Kernal: 1.2",
        setfsuid32: "Kernal: 2.4",
        setgid32: "Kernal: 2.4",
        setgroups32: "Kernal: 2.4",
        sethae: "Kernal: 2.0 ",
        setns: "Kernal: 3.0",
        setpgrp: "Kernal: 2.0 ",
        setregid32: "Kernal: 2.4",
        setresgid: "Kernal: 2.2",
        setresgid32: "Kernal: 2.4",
        setresuid: "Kernal: 2.2",
        setresuid32: "Kernal: 2.4",
        setreuid32: "Kernal: 2.4",
        setsockopt: "Kernal: 2.0 ",
        setuid32: "Kernal: 2.4",
        setup: "Kernal: 1.0 ",
        setxattr: "Kernal: 2.6; 2.4.18",
        shmat: "Kernal: 2.0 ",
        shmctl: "Kernal: 2.0 ",
        shmdt: "Kernal: 2.0 ",
        shmget: "Kernal: 2.0 ",
        shutdown: "Kernal: 2.0 ",
        sigaltstack: "Kernal: 2.2",
        signalfd: "Kernal: 2.6.22",
        signalfd4: "Kernal: 2.6.27",
        socket: "Kernal: 2.0 ",
        socketpair: "Kernal: 2.0 ",
        spill: "Kernal: 2.6.13 ",
        splice: "Kernal: 2.6.17",
        spu_create: "Kernal: 2.6.16 ",
        spu_run: "Kernal: 2.6.16 ",
        stat64: "Kernal: 2.4",
        statfs64: "Kernal: 2.6",
        statx: "Kernal: 4.11",
        subpage_prot: "Kernal: 2.6.25 ",
        swapcontext: "Kernal: 2.6.3 ",
        switch_endian: "Kernal: 4.1 ",
        symlinkat: "Kernal: 2.6.16",
        sync_file_range: "Kernal: 2.6.17",
        sync_file_range2: "Kernal: 2.6.22",
        syncfs: "Kernal: 2.6.39",
        sys_debug_setcontext: "Kernal: 2.6.11 ",
        syscall: "Kernal: 1.0 ",
        sysfs: "Kernal: 1.2",
        sysmips: "Kernal: 2.6.0 ",
        tee: "Kernal: 2.6.17",
        tgkill: "Kernal: 2.6",
        timer_create: "Kernal: 2.6",
        timer_delete: "Kernal: 2.6",
        timer_getoverrun: "Kernal: 2.6",
        timer_gettime: "Kernal: 2.6",
        timer_settime: "Kernal: 2.6",
        timerfd_create: "Kernal: 2.6.25",
        timerfd_gettime: "Kernal: 2.6.25",
        timerfd_settime: "Kernal: 2.6.25",
        tkill: "Kernal: 2.6; 2.4.22",
        truncate64: "Kernal: 2.4",
        ugetrlimit: "Kernal: 2.4",
        umount2: "Kernal: 2.2",
        unlinkat: "Kernal: 2.6.16",
        unshare: "Kernal: 2.6.16",
        userfaultfd: "Kernal: 4.3",
        usr26: "Kernal: 2.4.8.1 ",
        usr32: "Kernal: 2.4.8.1 ",
        utimensat: "Kernal: 2.6.22",
        utimes: "Kernal: 2.2",
        utrap_install: "Kernal: 2.2 ",
        vfork: "Kernal: 2.2",
        vm86: "Kernal: 2.0.28; 2.2",
        vm86old: "Kernal: 1.0 ",
        vmsplice: "Kernal: 2.6.17",
        waitid: "Kernal: 2.6.10",
        writev: "Kernal: 2.0",
        xtensa: "Kernal: 2.6.13 ",
    },
};
