import { SystemdValueEnum } from "./types";

const section = "Unit";

export const valueEnum: SystemdValueEnum[] = [
    {
        directive: "CollectMode",
        section,
        values: ["inactive", "inactive-or-failed"],
    },
    {
        directive: "ConditionArchitecture",
        section,
        values: [
            "x86",
            "x86-64",
            "ppc",
            "ppc-le",
            "ppc64",
            "ppc64-le",
            "ia64",
            "parisc",
            "parisc64",
            "s390",
            "s390x",
            "sparc",
            "sparc64",
            "mips",
            "mips-le",
            "mips64",
            "mips64-le",
            "alpha",
            "arm",
            "arm-be",
            "arm64",
            "arm64-be",
            "sh",
            "sh64",
            "m68k",
            "tilegx",
            "cris",
            "arc",
            "arc-be",
            "native",
        ],
    },
    {
        directive: "ConditionVirtualization",
        section,
        values: ["vm", "container"],
    },
    {
        directive: "FailureAction",
        section,
        values: [
            "none",
            "reboot",
            "reboot-force",
            "reboot-immediate",
            "poweroff",
            "poweroff-force",
            "poweroff-immediate",
            "exit",
            "exit-force",
            "soft-reboot",
            "soft-reboot-force",
            "kexec",
            "kexec-force",
            "halt",
            "halt-force",
            "halt-immediate",
        ],
    },
];
