<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>mkosi configuration file</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#mkosiComments</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#mkosiSections</string>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.config-entry.systemd</string>
      <key>begin</key>
      <string>^\s*(@)?([\w\-\.]+)\s*(=)[ \t]*</string>
      <key>end</key>
      <string>^(?![ \t]+)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.prefix.systemd</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.tag</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.assignment</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#mkosiComments</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#variables</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#quotedString</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#booleans</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#timeSpans</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#sizes</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numbers</string>
        </dict>
      </array>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>mkosiComments</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>comment.line.number-sign</string>
          <key>match</key>
          <string>#.*\n</string>
        </dict>
      </array>
    </dict>
    <key>mkosiSections</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>entity.name.section</string>
          <key>match</key>
          <string>^\s*\[(Config|Content|Distribution|Host|Match|Output|Validation)\]</string>
        </dict>
        <dict>
          <key>name</key>
          <string>entity.name.unknown-section</string>
          <key>match</key>
          <string>\s*\[[\w-]+\]</string>
        </dict>
      </array>
    </dict>
    <key>timeSpans</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>constant.numeric</string>
          <key>match</key>
          <string>\b(?:\d+(?:[uμ]s(?:ec)?|ms(?:ec)?|s(?:ec|econds?)?|m(?:in|inutes?)?|h(?:r|ours?)?|d(?:ays?)?|w(?:eeks)?|M|months?|y(?:ears?)?)){1,}\b</string>
        </dict>
      </array>
    </dict>
    <key>numbers</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>constant.numeric</string>
          <key>match</key>
          <string>(?&lt;=\s|=)\d+(?:\.\d+)?(?=[\s:]|$)</string>
        </dict>
      </array>
    </dict>
    <key>sizes</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>constant.numeric</string>
          <key>match</key>
          <string>(?&lt;=\s|=)\d+(?:\.\d+)?[KMGT](?=[\s:]|$)</string>
        </dict>
        <dict>
          <key>name</key>
          <string>constant.numeric</string>
          <key>match</key>
          <string>(?&lt;==)infinity(?=[\s:]|$)</string>
        </dict>
      </array>
    </dict>
    <key>quotedString</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>string.quoted.single</string>
          <key>begin</key>
          <string>(?&lt;=\G|\s)'</string>
          <key>end</key>
          <string>['\n]</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>name</key>
              <string>constant.character.escape</string>
              <key>match</key>
              <string>\\(?:[abfnrtvs\\"'\n]|x[0-9A-Fa-f]{2}|[0-8]{3}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>name</key>
          <string>string.quoted.double</string>
          <key>begin</key>
          <string>(?&lt;=\G|\s)"</string>
          <key>end</key>
          <string>["\n]</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>name</key>
              <string>constant.character.escape</string>
              <key>match</key>
              <string>\\(?:[abfnrtvs\\"'\n]|x[0-9A-Fa-f]{2}|[0-8]{3}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>booleans</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>constant.language</string>
          <key>match</key>
          <string>\b(?&lt;![-\/\.])(true|false|on|off|yes|no)(?![-\/\.])\b</string>
        </dict>
      </array>
    </dict>
    <key>variables</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\$)([A-Za-z0-9\_]+)\b</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.variable.systemd</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.other</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$\{)([A-Za-z0-9\_]+)(\})</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.variable.systemd</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.other</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.variable.systemd</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>name</key>
          <string>constant.other.placeholder</string>
          <key>match</key>
          <string>%%</string>
        </dict>
        <dict>
          <key>name</key>
          <string>constant.other.placeholder</string>
          <key>match</key>
          <string>%[aAbBCEfgGhHiIjJlLmMnNopPsStTuUvVwW]\b</string>
        </dict>
      </array>
    </dict>
  </dict>
  <key>scopeName</key>
  <string>source.mkosi</string>
  <key>uuid</key>
  <string>def576f2-a56e-400c-9a22-f014ceef415f</string>
</dict>
</plist>
