name: build-artifact
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install
        run: corepack enable && yarn install
      - name: Test
        run: yarn test && yarn build:ts && yarn build:syntax
      - name: Lint
        run: yarn lint
      - name: Bundle and Pack Package
        run: yarn build:vsix
      - uses: actions/upload-artifact@v4
        with:
          name: vscode-extension
          path: |
            artifacts/vscode/*.vsix
            artifacts/vscode/*.list
