name: build-artifact
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test && yarn build:syntax
      - name: Lint
        run: yarn lint
      - name: Bundle
        run: yarn run bundle
      - name: Pack Packages
        run: bash ./scripts/build-vscode-artifact.sh
      - uses: actions/upload-artifact@v3
        with:
          name: vscode-extension
          path: |
            artifacts/vscode/*.vsix
            artifacts/vscode/*.list
