name: build-artifact
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install and build
        run: |
          yarn install &&
          yarn run build:debug &&
          yarn run clean &&
          yarn run build:webpack &&
          yarn run lint
      - name: Build packages
        run: |
          yarn add --dev vsce &&
          bash ./scripts/build-vscode-artifact.sh
      - uses: actions/upload-artifact@v2
        with:
          name: vscode-extension
          path: |
            artifacts/vscode/*.vsix
            artifacts/vscode/*.list
