name: publish-vscode-extension
on:
  # Only publish vscode extension manually
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: corepack enable && yarn install
      - name: Publish Extension to Visual Studio Code Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: bash scripts/vsce.sh publish

